import Link from "next/link";
import type { FinalResearchResponse } from "@/types/research";
import { ConfidenceBadge } from "./EvidenceBadge";
import { QualityScoreCard } from "./QualityScoreCard";
import { CompetitorTable } from "./CompetitorTable";
import { BuyerPainCard } from "./BuyerPainCard";
import { SeoAeoCard } from "./SeoAeoCard";
import { WarningPanel } from "./WarningPanel";
import { ExportButtons } from "./ExportButtons";
import { SearchStatusBanner } from "./SearchStatusBanner";
import { SectionCard } from "./SectionCard";
import { HowResearched } from "./HowResearched";

function BulletList({ items }: { items: string[] }) {
  if (items.length === 0) return <p className="text-sm text-zinc-400">Nothing found.</p>;
  return (
    <ul className="list-disc space-y-1.5 pl-5 text-sm text-zinc-700">
      {items.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  );
}

export function ResultsDashboard({ report }: { report: FinalResearchResponse }) {
  return (
    <div id="dashboard-print-area" className="space-y-5">
      <div className="no-print flex flex-wrap items-center justify-between gap-3">
        <Link href="/" className="text-sm font-medium text-zinc-500 hover:text-zinc-900">
          ← New research
        </Link>
        <ExportButtons report={report} />
      </div>

      <SearchStatusBanner status={report.meta.searchStatus} sourcesCount={report.meta.sourcesCount} />

      <h1 className="text-2xl font-bold tracking-tight text-zinc-900 sm:text-3xl">
        {report.final.title}
      </h1>
      <p className="text-sm text-zinc-500">
        Brief: {report.final.briefSummary || report.brief.query}
      </p>

      <QualityScoreCard scores={report.scores} />

      <SectionCard
        title="Category summary"
        subtitle="What this market is and what problem it solves."
        badge={<ConfidenceBadge level={report.category.confidence} />}
      >
        <div className="space-y-3 text-sm text-zinc-700">
          <p>{report.category.summary}</p>
          {report.category.problemSolved && (
            <p>
              <span className="font-medium text-zinc-900">Problem solved: </span>
              {report.category.problemSolved}
            </p>
          )}
          {report.category.typicalBuyers.length > 0 && (
            <p>
              <span className="font-medium text-zinc-900">Typical buyers: </span>
              {report.category.typicalBuyers.join(" · ")}
            </p>
          )}
          {report.category.language.length > 0 && (
            <p>
              <span className="font-medium text-zinc-900">Category language: </span>
              {report.category.language.join(", ")}
            </p>
          )}
          <p className="text-xs text-zinc-400">Evidence: {report.category.sourceNote}</p>
        </div>
      </SectionCard>

      <SectionCard
        title="Competitor map"
        subtitle="Direct, indirect, and status-quo alternatives a buyer would compare."
      >
        <CompetitorTable competitors={report.competitors.competitors} />
      </SectionCard>

      <SectionCard
        title="Buyer pain themes"
        subtitle="Repeated pains in customer language, with marketing implications."
      >
        <BuyerPainCard pains={report.pains.pains} />
      </SectionCard>

      <SectionCard title="Messaging patterns" subtitle="What competitors commonly say.">
        <BulletList items={report.final.messagingPatterns} />
      </SectionCard>

      <SectionCard
        title="Positioning opportunities"
        subtitle="Where a new entrant could sound different or sharper."
      >
        <BulletList items={report.final.positioningOpportunities} />
      </SectionCard>

      <SectionCard
        title="SEO / AEO opportunities"
        subtitle="Keywords, buyer questions, comparisons, and answer-engine topics."
      >
        <SeoAeoCard seo={report.seo} />
      </SectionCard>

      <WarningPanel verification={report.verification} />

      <HowResearched report={report} />

      <footer className="pb-4 text-center text-xs text-zinc-400">
        Generated by Market Proof ({report.meta.provider}/{report.meta.model}) in{" "}
        {Math.round(report.meta.durationMs / 1000)}s · Scores are interpretive guidance, not
        precise measurements.
      </footer>
    </div>
  );
}
