/**
 * Builds the standalone Markdown document for copy/export.
 *
 * Reuses the synthesis markdown and appends machine-generated audit +
 * sources sections so the exported file carries the "receipts" with it.
 */
import type { FinalResearchResponse } from "@/types/research";

export function buildMarkdown(r: FinalResearchResponse): string {
  const s = r.scores;
  const lines = [
    r.final.markdown.trim(),
    "",
    "---",
    "",
    "## Research Quality Audit (generated rubric)",
    "",
    `- Overall: ${s.overall}/10`,
    `- Competitor coverage: ${s.competitorCoverage}/10`,
    `- Source quality: ${s.sourceQuality}/10`,
    `- Buyer pain specificity: ${s.buyerPainSpecificity}/10`,
    `- Evidence coverage: ${s.evidenceCoverage}/10`,
    `- Marketing usefulness: ${s.marketingUsefulness}/10`,
    `- Overclaiming risk: ${s.overclaimRisk}`,
    "",
    "## Verification notes",
    "",
    ...r.verification.unsupportedClaims.map((c) => `- UNSUPPORTED: ${c.claim} — ${c.reason}`),
    ...r.verification.weakClaims.map((c) => `- WEAK: ${c.claim} — ${c.reason}`),
    ...(r.verification.unsupportedClaims.length + r.verification.weakClaims.length === 0
      ? ["- No unsupported or weak claims flagged."]
      : []),
    "",
    "## Human review checklist",
    "",
    ...r.verification.humanChecklist.map((c) => `- [ ] ${c}`),
    "",
    "---",
    "",
    `_Generated by Market Proof (${r.meta.provider}/${r.meta.model}) on ${r.meta.createdAt}. `,
    `Sources: ${r.meta.searchStatus === "live" ? `${r.meta.sourcesCount} live web sources` : "model knowledge only — verify before use"}.` +
      "_ Scores are interpretive, not precise measurements._",
    "",
  ];
  return lines.join("\n");
}

export async function copyText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function downloadMarkdown(filename: string, text: string): void {
  const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
